### ISSUE TITLE
Errors when testing the train.py with tensorflow as backend

### ISSUE THREAD

**Issue by zhangyu2ustc** [tkipf/keras-gcn#27] opened 2018-02-14 19:48 UTC
Sorry, the previous issue report was closed. So I created a new one.

The error message showed up again when I change the FILTER method from 'localpool' to 'chebyshev' even by running "python train.py" from terminal.

ValueError: Dimensions must be equal, but are 4299 and 1433 for 'graph_convolution_1/MatMul' (op: 'MatMul') with input shapes: [?,4299], [1433,16].

**Comment by tkipf** [comment] 2018-02-14 19:50
Duplicate of https://github.com/tkipf/keras-gcn/issues/26

**Closed by tkipf** 2018-02-14 19:50 UTC
