### ISSUE TITLE
Errors occur during the training using chebyshev way

### ISSUE THREAD

**Issue by liuenda** [tkipf/keras-gcn#28] opened 2018-02-23 11:04 UTC
Hi
I am very interested in your work. 
It trains well using the default filter (localpool)
But failed to run when I change the code to:
```python
FILTER = 'chebyshev'  # 'chebyshev'
```
The environment I use is:

tensorflow==1.5.0
tensorflow-tensorboard==1.5.1
Keras==2.1.4

And here is the error:
```bash
(py36) liu@pattaya:~/download/keras-gcn/kegra$ python train.py
/home/liu/miniconda3/envs/py36/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.
Loading cora dataset...
Dataset has 2708 nodes, 5429 edges, 1433 features.
Using Chebyshev polynomial basis filters...
Calculating largest eigenvalue of normalized graph Laplacian...
Calculating Chebyshev polynomials up to order 2...
Traceback (most recent call last):
  File "/home/liu/miniconda3/envs/py36/lib/python3.6/site-packages/tensorflow/python/framework/common_shapes.py", line 686, in _call_cpp_shape_fn_impl
    input_tensors_as_shapes, status)
  File "/home/liu/miniconda3/envs/py36/lib/python3.6/site-packages/tensorflow/python/framework/errors_impl.py", line 473, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.InvalidArgumentError: Dimensions must be equal, but are 4299 and 1433 for 'graph_convolution_1/MatMul' (op: 'MatMul') with input shapes: [?,4299], [1433,16].

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "train.py", line 55, in <module>
    H = GraphConvolution(16, support, activation='relu', kernel_regularizer=l2(5e-4))([H]+G)
  File "/home/liu/miniconda3/envs/py36/lib/python3.6/site-packages/keras/engine/topology.py", line 617, in __call__
    output = self.call(inputs, **kwargs)
  File "/home/liu/miniconda3/envs/py36/lib/python3.6/site-packages/kegra/layers/graph.py", line 73, in call
    output = K.dot(supports, self.kernel)
  File "/home/liu/miniconda3/envs/py36/lib/python3.6/site-packages/keras/backend/tensorflow_backend.py", line 1072, in dot
    out = tf.matmul(x, y)
  File "/home/liu/miniconda3/envs/py36/lib/python3.6/site-packages/tensorflow/python/ops/math_ops.py", line 2022, in matmul
    a, b, transpose_a=transpose_a, transpose_b=transpose_b, name=name)
  File "/home/liu/miniconda3/envs/py36/lib/python3.6/site-packages/tensorflow/python/ops/gen_math_ops.py", line 2516, in _mat_mul
    name=name)
  File "/home/liu/miniconda3/envs/py36/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/home/liu/miniconda3/envs/py36/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 3162, in create_op
    compute_device=compute_device)
  File "/home/liu/miniconda3/envs/py36/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 3208, in _create_op_helper
    set_shapes_for_outputs(op)
  File "/home/liu/miniconda3/envs/py36/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 2427, in set_shapes_for_outputs
    return _set_shapes_for_outputs(op)
  File "/home/liu/miniconda3/envs/py36/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 2400, in _set_shapes_for_outputs
    shapes = shape_func(op)
  File "/home/liu/miniconda3/envs/py36/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 2330, in call_with_requiring
    return call_cpp_shape_fn(op, require_shape_fn=True)
  File "/home/liu/miniconda3/envs/py36/lib/python3.6/site-packages/tensorflow/python/framework/common_shapes.py", line 627, in call_cpp_shape_fn
    require_shape_fn)
  File "/home/liu/miniconda3/envs/py36/lib/python3.6/site-packages/tensorflow/python/framework/common_shapes.py", line 691, in _call_cpp_shape_fn_impl
    raise ValueError(err.message)
ValueError: Dimensions must be equal, but are 4299 and 1433 for 'graph_convolution_1/MatMul' (op: 'MatMul') with input shapes: [?,4299], [1433,16].
(py36) liu@pattaya:~/download/keras-gcn/kegra$
```

Look forward to your reply. 
Thank you very much.

**Comment by tkipf** [comment] 2018-02-23 11:07
Thanks for catching this. I might want to remove this support from this repository as it is quite time consuming to ensure compatibility with all version updates. You can use https://github.com/tkipf/gcn if you'd like to make use of this particular filter.

**Comment by tkipf** [comment] 2018-02-23 11:07
Duplicate of https://github.com/tkipf/keras-gcn/issues/26

**Comment by liuenda** [comment] 2018-02-26 08:11
Hi tkipf, thank you for your reply! 
It is really annoying for the incompatible version of Leras and other tools. I really understand.
Could do please tell me the (or just use ```python pip freeze ```  ) the last compatible version number in order to run this script?

I can adjust my package versions for my environment.

Thank you very much!

**Comment by tkipf** [comment] 2018-02-26 08:17
You can try this version of the repository: https://github.com/tkipf/keras-gcn/tree/dfdf5ef9e658a3e2e7c09bc39c950a81c7846d6f

Along with keras 1.2.1 and TensorFlow 0.90. Hope this works.

**Comment by tkipf** [comment] 2018-02-26 12:53
Fixed with https://github.com/tkipf/keras-gcn/commit/eb89564a0e865640c11283991685d80c84bc602a

**Closed by tkipf** 2018-02-26 12:53 UTC
